// GENERATED by tools/gen_mascot_table.py -- do not edit by hand.
// Source of truth: pc_app/mascot_faces.py. Re-run the generator after editing it.
//
// One expression per (status, tone). The tone is applied on top of the status and is
// allowed to override it -- that is what makes sarcasm mode read as unimpressed even
// while the presence badge is green.
#pragma once

#include <Arduino.h>

enum class Idle : uint8_t { Bob, Sway, Slump, Sleep, Bounce, Twitch, Count };

struct Face {
  int8_t browTilt;     // -100 furrowed .. +100 raised
  uint8_t eyeOpen;     // 0 shut .. 100 wide; under ~50 reads as unimpressed
  int8_t mouthCurve;   // -100 frown .. +100 grin
  uint8_t mouthOpen;   // 0 closed .. 100 wide; a little of this reads as talking
  bool browAsym;       // one brow up, one down
  bool blush;
  Idle idle;
};

constexpr uint8_t kFaceStatusCount = 9;
constexpr uint8_t kFaceToneCount = 3;

// Indexed [Status][Tone], both in enum order.
constexpr Face kFaces[kFaceStatusCount][kFaceToneCount] = {
    // available
    {{10, 100, 70, 0, false, false, Idle::Bob},
     {60, 45, -15, 0, true, false, Idle::Slump},
     {30, 100, 90, 40, false, true, Idle::Bounce}},
    // busy
    {{-30, 85, -10, 0, false, false, Idle::Sway},
     {60, 45, -15, 0, true, false, Idle::Slump},
     {30, 100, 90, 40, false, true, Idle::Bounce}},
    // in_meeting
    {{-10, 70, 0, 35, false, false, Idle::Sway},
     {60, 45, -15, 0, true, false, Idle::Slump},
     {30, 100, 90, 40, false, true, Idle::Bounce}},
    // dnd
    {{-70, 60, -60, 0, false, false, Idle::Slump},
     {60, 45, -15, 0, true, false, Idle::Slump},
     {30, 100, 90, 40, false, true, Idle::Bounce}},
    // away
    {{0, 20, 0, 0, false, false, Idle::Sleep},
     {60, 20, -15, 0, true, false, Idle::Sleep},
     {30, 100, 90, 40, false, true, Idle::Bounce}},
    // brb
    {{20, 45, 20, 0, false, false, Idle::Sleep},
     {60, 45, -15, 0, true, false, Idle::Sleep},
     {30, 100, 90, 40, false, true, Idle::Bounce}},
    // offline
    {{-10, 0, -20, 0, false, false, Idle::Sleep},
     {60, 0, -15, 0, true, false, Idle::Sleep},
     {30, 100, 90, 40, false, true, Idle::Bounce}},
    // unknown
    {{40, 90, 0, 20, false, false, Idle::Twitch},
     {60, 45, -15, 0, true, false, Idle::Twitch},
     {30, 100, 90, 40, false, true, Idle::Bounce}},
    // disconnected
    {{-20, 30, -40, 0, false, false, Idle::Twitch},
     {60, 30, -15, 0, true, false, Idle::Twitch},
     {30, 100, 90, 40, false, true, Idle::Bounce}},
};
