"""Compile pc_app/mascot_faces.py into the C table the firmware reads.

    python tools/gen_mascot_table.py           # rewrite firmware/src/mascot_table.h
    python tools/gen_mascot_table.py --check   # fail if it is out of date (used by the tests)

The expressions are authored once, in Python, because two things need them: the firmware draws
them on the panel and the GUI draws them in its preview. Generating one side from the other is
the only way to be sure a face tweak reaches both.
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO))

from pc_app.i18n import TONES  # noqa: E402
from pc_app.mascot_faces import IDLES, STATUS_NAMES, face_for  # noqa: E402

HEADER = REPO / "firmware" / "src" / "mascot_table.h"

BANNER = "// GENERATED by tools/gen_mascot_table.py -- do not edit by hand."


def _idle_enum() -> str:
    names = ", ".join(name.capitalize() for name in IDLES)
    return f"enum class Idle : uint8_t {{ {names}, Count }};"


def render() -> str:
    lines = [
        BANNER,
        "// Source of truth: pc_app/mascot_faces.py. Re-run the generator after editing it.",
        "//",
        "// One expression per (status, tone). The tone is applied on top of the status and is",
        "// allowed to override it -- that is what makes sarcasm mode read as unimpressed even",
        "// while the presence badge is green.",
        "#pragma once",
        "",
        "#include <Arduino.h>",
        "",
        _idle_enum(),
        "",
        "struct Face {",
        "  int8_t browTilt;     // -100 furrowed .. +100 raised",
        "  uint8_t eyeOpen;     // 0 shut .. 100 wide; under ~50 reads as unimpressed",
        "  int8_t mouthCurve;   // -100 frown .. +100 grin",
        "  uint8_t mouthOpen;   // 0 closed .. 100 wide; a little of this reads as talking",
        "  bool browAsym;       // one brow up, one down",
        "  bool blush;",
        "  Idle idle;",
        "};",
        "",
        f"constexpr uint8_t kFaceStatusCount = {len(STATUS_NAMES)};",
        f"constexpr uint8_t kFaceToneCount = {len(TONES)};",
        "",
        "// Indexed [Status][Tone], both in enum order.",
        "constexpr Face kFaces[kFaceStatusCount][kFaceToneCount] = {",
    ]

    for status in STATUS_NAMES:
        lines.append(f"    // {status}")
        row = []
        for tone in TONES:
            face = face_for(status, tone)
            row.append(
                "{{{}, {}, {}, {}, {}, {}, Idle::{}}}".format(
                    face.brow_tilt,
                    face.eye_open,
                    face.mouth_curve,
                    face.mouth_open,
                    "true" if face.brow_asym else "false",
                    "true" if face.blush else "false",
                    face.idle.capitalize(),
                )
            )
        lines.append("    {" + ",\n     ".join(row) + "},")

    lines.append("};")
    lines.append("")
    return "\n".join(lines)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="do not write; exit non-zero if the checked-in header is stale",
    )
    args = parser.parse_args(argv)

    generated = render()
    current = HEADER.read_text(encoding="utf-8") if HEADER.exists() else ""

    if args.check:
        if current == generated:
            print(f"{HEADER.relative_to(REPO)} is up to date")
            return 0
        print(
            f"{HEADER.relative_to(REPO)} is stale -- run: python tools/gen_mascot_table.py",
            file=sys.stderr,
        )
        return 1

    if current == generated:
        print(f"{HEADER.relative_to(REPO)} already up to date")
        return 0
    HEADER.parent.mkdir(parents=True, exist_ok=True)
    HEADER.write_text(generated, encoding="utf-8", newline="\n")
    print(f"wrote {HEADER.relative_to(REPO)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
